### ISSUE TITLE
Bug: pay_customers column regenerates schema incorrectly

### ISSUE THREAD

**Issue by jacobdaddario** [joemasilotti/railsdevs.com#192] opened 2021-12-29 00:31 UTC
**Describe the bug**
When regenerating the database using `rails db:prepare`, the schema loses the precision of the `deleted_at` column that was present in the committed schema.

**To Reproduce**
1. Run `bin/setup`.
2. Check `git status` to see altered schema.

**Expected behavior**
The committed schema should be unchanged when the setup script is run with no new migrations.

**Comment by joemasilotti** [comment] 2021-12-29 01:42
Hmm is this a bug in Pay or our integration? The migration wasn't touched after generating it.

**Comment by jacobdaddario** [comment] 2021-12-29 01:51
It might be a Pay bug. I wonder if @excid3 knows anything about this.

**Comment by joemasilotti** [comment] 2021-12-29 16:35
It looks like this can be fixed by making the migration a Rails 7 one, instead of Rails 6. Can you try `main` and reopen if it doesn't work?

**Comment by jacobdaddario** [comment] 2021-12-30 04:34
I pulled from main, and still had the same issue. Ultimately it's not a huge deal, but I imagine you'll probably run into people accidentally committing changes to the schema.

**Comment by joemasilotti** [comment] 2021-12-30 05:40
Reopened. I'd love to figure this out - not sure what's going on though.

**Comment by joemasilotti** [comment] 2022-01-30 02:44
This seems to have worked itself out? I can't reproduce it so I'm going to close it out. If it pops up again feel free to comment below and I will reopen.

**Closed by joemasilotti** 2022-01-30 02:44 UTC
Labels: bug, help wanted
