### ISSUE TITLE
Notification UI

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#154] opened 2021-12-15 23:27 UTC
- [ ] A developer or business can view their _unread_ notifications via a link from the navigation bar
- [ ] When a notification is clicked, `read_at` is set

**Comment by jayeclark** [comment] 2021-12-16 20:27
Hi there! I've got PR #162 in progress for the notification badge and realized it probably makes the most sense to work on #155 and this issue concurrently.

I had a few questions on design. 

- **Were you envisioning that the UI would be similar to the conversations UI?** (i.e. user clicks on notifications badge and a new page comes up with their notifications.) Or were you instead envisioning a dropdown on the badge summarizing recent notifications (with the option to dismiss each) and an option at the bottom to 'view all / view more' which would route to a conversations-style page?
- **Should a notification be considered 'read' when they it is displayed to the user?** Or does the user physically need to interact with the notification by expanding it or by marking it as read?
- **Should there be an option to delete a notification, or should notifications get automatically 'deleted' once they are read?** 
- **What general types of notifications will users be receiving?** How long on average / what format? (ie will it just be a message or will there also be a title? ) 
- **Should there be different behavior for different notifications?** For example, should a notification about a new message contain a link to the conversations page? Should there be success/warning/error/neutral styling based on notification type?
- Are there any boilerplate db entries for notifications that I can use for testing/development?
- And, just to double check... the kinds of notifications that appear on the page when creating or saving ones profile or after creating and account or sending a message are NOT the kind of notifications that this issue is intended to address, right?

**Comment by joemasilotti** [comment] 2021-12-16 20:44
Great questions, thanks for diving in and forcing some decisions.

* UI-wise, let's keep this as simple as possible. To me, that means a new screen when you click the badge. We can always (later) move this to a drop-down that is powered by a lazy-loaded Turbo frame. Design-wise, `/conversations` should be good to model after.
* A notification should be considered "read" when it is interacted with, i.e. clicked.
* Let's only show unread notifications on the new screen, so no need to worry about deleting them.
* Right now the only notifications are for new messages. Assuming the notification has a param with `message` of type `Message`, they can be formatted like so: `"#{notification.message.sender.hero} sent you a message."` No need to dive in to the body of the message just yet.
* There is only one type of notification right now, so no need to differentiate anything. These can be linked directly to the conversation page of the message. They can all be styled "neutral" without any indicating colors.
* There are currently no boilerplate db entries for notifications.
* Correct, these notifications are only for a new message, nothing to do with the admin notifications regarding a new developer/business signing up.

Let me know if I missed anything! Outside of that, `noticed` can be used to model the new notifications and a new `Message` should only trigger a notification for the recipient (not the sender).

**Comment by jayeclark** [comment] 2021-12-16 20:51
This is great, thanks! Definitely enough for me to get started. I'll open a draft PR after I have the basics in place, just to check that the direction and basic functionality are what was intended. (Since this is a bit more complicated than the badge issue, it might not be until early next week.)

**Comment by joemasilotti** [comment] 2021-12-16 21:14
Sounds great on all accounts, thank you!

**Comment by joemasilotti** [comment] 2021-12-17 22:40
Oh, one more thought. you will probably _also_ knock out #151 by implementing this! Feel free to submit a PR for that first, if it is easier for you.

**Comment by joemasilotti** [comment] 2021-12-21 13:41
Heads up, I took care of #151 and #156 which close up the MVP for business subscriptions. Feel free to merge `main` into your work to get the updates!

**Comment by jayeclark** [comment] 2021-12-22 16:23
OK great! I got a little sidetracked over the weekend/early this week with holiday stuff but am hoping to get back on this in the afternoon today.

**Comment by joemasilotti** [comment] 2021-12-22 16:28
Sounds great! And no worries, excited to see what you build.

**Comment by jayeclark** [comment] 2021-12-23 14:40
I'm having a little trouble getting the dev server running again now that I've merged in the payment-related commits. (Stripe needs to be configured whether or not one is working on payment related code.)

Maybe you can save me some time - I'm poking around and see if I can find it in the code but haven't found it yet. What is the webhook endpoint that I should be using to generate the webhook signing secret?

**Comment by jayeclark** [comment] 2021-12-23 14:45
NVM, found it! Still getting errors trying to start the dev server though.

**Comment by joemasilotti** [comment] 2021-12-23 15:09
What error are you seeing now? And would you mind adding webhook instructions to the README? I thought I added everything you need from a fresh install but must have missed something.

**Comment by jayeclark** [comment] 2021-12-23 15:26
I sorted it out, turned out to be a problem caused by not having the right editor to edit the development.yml.enc file.

**Closed** 2022-01-01 21:55 UTC
Labels: enhancement, help wanted
