### ISSUE TITLE
After setup, every test results in a PG::ForeignKeyViolation

### ISSUE THREAD

**Issue by fpsvogel** [joemasilotti/railsdevs.com#178] opened 2021-12-22 14:04 UTC
**Describe the bug**
After forking and cloning the project for the first time, I followed the setup steps and I'm able to run locally with `bin/dev`. But I can't run the tests because every test results in this error:

```
DRb::DRbRemoteError: PG::ForeignKeyViolation: ERROR:  insert or update on table "active_storage_attachments" violates foreign key constraint "fk_rails_c3b3935057"
DETAIL:  Key (blob_id)=(980190962) is not present in table "active_storage_blobs".
```

I'm on Ubuntu 20.04 in WSL.

**To Reproduce**
1. Clone the railsdevs.com repo.
2. Follow the setup steps in the README.
3. Run `rails test`.
4. See the errors.

**Expected behavior**
The tests should run without errors.

**Additional context**
I'm pretty new to open source (this will be my third contribution ever), so it's possible that I'm missing a basic setup step. But I double-checked to make sure I followed all the steps in the README.

I tried running `rails db:reset` but that didn't make a difference.

**Screenshots**

![image](https://user-images.githubusercontent.com/9300391/147104394-4dba21e1-2ddc-4f7e-a243-1cd5b29abbfb.png)

**Comment by jacobdaddario** [comment] 2021-12-23 00:48
I tested this out on my machine, and I didn't receive an error. That said, I've been working on uploads, and I wonder if that has something to do with it. It looks like it's missing the blobs for an attachment. What's the contents of your `blobs.yml` fixture? What's the content of your folder under `test/fixtures/files`?

**Comment by fpsvogel** [comment] 2021-12-23 02:46
Thanks for the help! Here's my `blobs.yml`:

```yaml
one: <%= ActiveStorage::FixtureSet.blob(
  filename: "lovelace.jpg"
) %>

two: <%= ActiveStorage::FixtureSet.blob(
  filename: "mountains.jpg"
) %>
```

My `test/fixtures/files` directory contains two images: `lovelace.jpg` and `mountains.jpg`.

**Comment by jacobdaddario** [comment] 2021-12-23 04:09
@fpsvogel Oh! This is simple, you're just missing the fixture responsible for the avatar of the business. Try pulling down the recent changes to the repository.

I'm not sure why the fixture didn't pull down when the changes to the test seem to have been pulled. Regardless, if you check the `blobs.yml` file in the repo on GitHub, you'll see what you're missing.

**Comment by fpsvogel** [comment] 2021-12-23 14:36
@jacobdaddario Thanks, I see I didn't have those recent changes. I pulled the main branch and reset my database, but I'm still seeing the same error. I double-checked that my `blobs.yml` matches the latest version, and it does. I'm stumped.

**Comment by jacobdaddario** [comment] 2021-12-23 14:48
Do you have the image that blob 3 is trying to reference?

**Comment by fpsvogel** [comment] 2021-12-23 15:10
Sorry, I forgot to mention that yes, now I do have the additional image as well. I also deleted my fork and then forked and cloned again from scratch, but I'm still getting the error.

**Comment by joemasilotti** [comment] 2021-12-23 15:13
This issue makes me think your database is still in a weird state. https://github.com/rails/rails/issues/37984

Can you confirm that killing the server and running `rails db:reset` doesn't nuke the orphan records?

**Comment by joemasilotti** [comment] 2021-12-23 15:18
Also maybe this will help?

https://stackoverflow.com/a/61337975

**Comment by fpsvogel** [comment] 2021-12-23 22:06
Thanks, Joe, for the ideas. Here's what I tried just now:

- `rails db:reset`
- went into the Postgres console and deleted the railsdevs DBs there, then created them again in Rails
- deleted `schema.rb` and tried the above again
- switched the project to Ruby 3.0.3 and Rails 7 release, and tried all of the above again

I also tried the StackOverflow answer, but that did nothing because there are no `ActiveStorage::Attachment`s in my database, either in test or development. I'm not sure what that means, but whatever the issue is, it seems to be different from those in the links.

**Comment by hungmi** [comment] 2021-12-24 09:12
Hi, I was trying to see if I can help.
1. I forked and cloned the repo
2. `bin/setup`
3. `rails test`
4. got lots of errors like `ActionView::Template::Error: The asset "application.css" is not present in the asset pipeline.`
5. start the server `foreman start -f Procfile.dev` and wait for the compiling.
6. `rails test` again and got all green (rainbow actually).

BTW, I am on MacOS 10.15.7

**Comment by jacobdaddario** [comment] 2021-12-24 14:50
This is actually expected, but it definitely is confusing. Let me explain. Rails is looking for a compiled stylesheet, which hasn't been created yet. When you run the dev server for the first time, it generates that sheet, so then tests pass.

@joemasilotti maybe we should alter the setup script to run bin/dev right off the bat after setup.
> 
> 4. got lots of errors like `ActionView::Template::Error: The asset "application.css" is not present in the asset pipeline.`
>

**Comment by joemasilotti** [comment] 2021-12-25 22:09
@jacobdaddario, I added two more steps to `bin/setup` to compile the assets. I think that should fix everything, I tested on a new clone and it worked for me.

@hungmi, can you give this a try? I pushed to `main`.

**Comment by joemasilotti** [comment] 2021-12-25 22:10
@fpsvogel, this is so weird! Sorry we haven't been able to help more.

After getting the error, can you try running the console or direct queries and seeing what the database is populated with? `active_storage_attachments` and `active_storage_blobs`, specifically.

**Comment by hungmi** [comment] 2021-12-26 13:35
> @hungmi, can you give this a try? I pushed to `main`.

It works perfectly! 👍
I can `git clone` & `bin/setup` & `bin/check` smoothly.

**Comment by fpsvogel** [comment] 2021-12-27 15:23
@joemasilotti That's OK, thanks for helping look into it! Especially during the holidays… and by the way, feel free not to answer right away.

I logged into the Postgres console and queried those two tables, and they are empty:

![image](https://user-images.githubusercontent.com/9300391/147485015-31d0d8c3-7d28-424e-b81a-fee153ea9c3f.png)

I tried the same in the databases `railsdevs_test-0` through `railsdevs_test-7` as well as `railsdevs_development`. Those are all the railsdevs databases that I see.

I also tried querying `ActiveStorage::Attachment.all` and `ActiveStorage::Blob.all` in the Rails console (development and test environments), and I got nothing there too.

**Comment by hungmi** [comment] 2021-12-27 17:25
@fpsvogel I can reproduce this using `multipass`.
I have tried Ubuntu 20.04 & 18.04, both with postgresql 12 & 14.
All failed with same error.

**Comment by fpsvogel** [comment] 2022-01-03 20:08
Thanks @hungmi. I'm running Ubuntu 20.04 in WSL. Based on your findings, it seems the issue is related to that. I don't have a Mac, or Ruby installed on Windows, so I'm not sure where to go from here. But I'd be happy to continue troubleshooting if anyone has ideas on what I could try next.

**Comment by joemasilotti** [comment] 2022-01-30 02:52
Hey @fpsvogel, I'm going to assume that `multipass` is the culprit and close this for now. If you have a more concrete solution or updates feel free to comment and I'll open it back up.

**Closed by joemasilotti** 2022-01-30 02:52 UTC
Labels: bug, help wanted

**Comment by fpsvogel** [comment] 2022-01-30 20:07
@joemasilotti Sorry, I should have been more clear in my last message. I'm running Ubuntu in WSL2, not in Multipass, which is a different VM manager. The common factor in my case and hungmi's is just that we ran Ubuntu. Whether the issue has anything to do with running Linux inside another OS, I don't know; the internals of WSL and Multipass are quite different, from what I understand. I'm hoping someone more knowledgeable on these things will run into the same issue in the future and know what to do. Thank you all for helping troubleshoot it, even if we weren't successful yet.
